### ISSUE TITLE
04. Add a high-pass filter

### ISSUE THREAD

**Issue by randompast** [mmckegg/web-audio-school#10]
As this is the first instance of having more than one node,

there should be some note about 
filter.connect(audioContext.destination)
oscillator.connect(filter)

to prevent mistakes of this type:
filter.connect(audioContext.destination)
oscillator.connect(audioContext.destination)

**Comment by mmckegg** [comment]
Very good point. I have witnessed quite a few instances of people getting stuck on this problem. 

I don't have time to work on this right now, but if anyone else wants to take a stab at it, I'll happily accept a pull request! :tractor:

**Comment by newswim** [comment]
+1 this tripped me up!

**Comment by gmschroeder** [comment]
#16 adds explanatory comments. @mmckegg isn't sure if this is something to work through yourself or a bona fide issue.
I see the value in working through it yourself, but this feels like a 'gotcha' more than an excercise in reasoning.
I'd be glad to write something or edit the existing pull request if I knew what/if would be accepted.

**Comment by mmckegg** [comment]
Hey @gmschroeder, @newswim and @joshuaalm! I've taken the feedback on board and ideas from #16 and [added a section about how `connect()` works to this lesson](https://github.com/mmckegg/web-audio-school/commit/ed45bba81b619a8a255a9789cd75802f10f097fc).

Let me know if you think this addresses the problem sufficiently 😃

**Comment by newswim** [comment]
This helped a lot, thank you so much. :heart_eyes_cat:

**Comment by mmckegg** [comment]
Awesome 😄 I'll close this issue then!
