### ISSUE TITLE
08. 09. ignores correct answer

### ISSUE THREAD

**Issue by soltao** [mmckegg/web-audio-school#17]
This course is lots of fun, I'm currently skipping 08, 09 and possibly more excercises with the same issue: even if I copy the correct answer from the source code, I can't seem to get the green button to move forward.

The same in Firefox and Chrome, I'm working on an old netbook too, I wonder if the load/encoding time for the audio (currently set as 0.2 as per the start.js file) should be adjusted.

Screenshot for reference: http://imgur.com/a/6ysjO

**Comment by probil** [comment]
It seems like your answer is not correct. Answer graph should be totally green.

I have passed 08 and 09 with no issue:
http://i.imgur.com/1RqJKtb.png

Maybe it's related to the windows
