### ISSUE TITLE
Fails to Start

### ISSUE THREAD

**Issue by GeorgeWL** [mmckegg/web-audio-school#21]
```cmd
$ web-audio-school
Starting server...
Go to http://localhost:9966
find: ‘/I’: No such file or directory
find: ‘/N’: No such file or directory
find: ‘SoundMixer.exe’: No such file or directory
find: ‘/I’: No such file or directory
find: ‘/N’: No such file or directory
find: ‘explorer.exe’: No such file or directory
```
I'm guessing it was originally designed for computers where you knew what drives would exist?

It makes it not great for running on other users PCs though. Maybe just have it `mkdir` in the location it was run from, and populate that with the required assets

**Comment by mmckegg** [comment]
Weird, I have no idea what the error is about!  Did you try to go to http://localhost:9966 manually?

What OS are you running?

This is also available online at https://mmckegg.github.io/web-audio-school/

**Comment by skratchdot** [comment]
Guessing it's probably this line: https://github.com/mmckegg/web-audio-school/blob/master/run.js#L10.  A cross-os solution to opening things could be: https://github.com/sindresorhus/opn

But like @mmckegg said, it'd be easiest to just use the online version.  Of couse you could try out a fix by running `npm install opn` locally, then changing line 10 to:
```
require('opn')('http://localhost:9966')
```
and seeing if things work

**Comment by mmckegg** [comment]
Oh yeah, that `open URL` will definitely be it!

Pull request accepted to use `opn`! 😆

**Comment by skratchdot** [comment]
Haha. Okay, I'll do it.  I was being super lazy, but just tested the change locally. PR in a sec.

**Comment by GeorgeWL** [comment]
awesome. so all working in the updated then?

 Windows 10 is the OS btw. Localhost doesn't load.

mostly wanted to run locally cause I prefer coding in my editor, rather than on an input in browser.

**Comment by skratchdot** [comment]
@GeorgeWL - Can you try installing v1.3.1 and seeing if it works on Windows 10?  I only confirmed it still works on OSX, but couldn't test Windows (just confirmed that `run.js` *looked* like it should work to me).

**Comment by GeorgeWL** [comment]
through npm or direct from here @skratchdot ?

**Comment by skratchdot** [comment]
I meant via npm:
```
npm install web-audio-school -g
```
Then start it:
```
web-audio-school
```
