### ISSUE TITLE
Looping Doesn't Stop on Latest Firefox Developer Edition

### ISSUE THREAD

**Issue by hokey** [mmckegg/web-audio-school#5]
Using 40.0a2 (2015-06-10) on Mac OS X Yosemite, both the target and user audio does not stop looping even though a duration is set.

**Comment by mmckegg** [comment]
Interesting: https://github.com/WebAudio/web-audio-api/issues/421

Seems that this functionality was undefined in the Web Audio spec. Firefox did the opposite to chrome. 

I could just switch the lesson to use an explicit `player.stop()`.

**Comment by mmckegg** [comment]
addressed in v1.0.3

Thanks for reporting!!
