### ISSUE TITLE
Not working in Safari (no AudioContext found)

### ISSUE THREAD

**Issue by herrherrmann** [mmckegg/web-audio-school#7]
Hey there,

today at the web audio hackday we noticed that the website doesn't render in Safari because there's no AudioContext found. Maybe this can be solved through vendor-prefixing or something? Or does even the current Safari not support any AudioContext?

Thanks for your awesome work though!

![safari](https://cloud.githubusercontent.com/assets/6429568/10119510/602cf5ee-6498-11e5-9b16-ded55553f3d7.png)

**Update:**
Oops, I just noticed you're even mentioning this bug in the [readme](https://github.com/mmckegg/web-audio-school#browser-support). But maybe you still want to keep this issue open until it's fixed?

**Comment by ahdinosaur** [comment]
hey @herrherrmann. :cat:  [it seems Safari supports web audio under a vendor prefix](http://caniuse.com/audio-api/embed/). i made a [quick PR that might fix this](https://github.com/mmckegg/web-audio-school/issues/8), maybe worth checking out.

**Comment by mmckegg** [comment]
@ahdinosaur: Just tried out the PR. Gets past the initial load, but nothing else works. 

Safari also doesn't support unprefixed flex-box, and is missing some stuff in the web audio api such as stereo panner. It is probably possible to get it working, but I don't think it's worth it. 

I think it will probably work in the new Safari 9 coming out in a few days (with thew new Mac OS release).

**Comment by mmckegg** [comment]
Will work on iOS too once https://github.com/thlorenz/brace/pull/45 lands.
